### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by rctneil** [salsita/chili#10]
Could this be added to Bower by any chance?

**Comment by ghost** [comment]
Sure! Will add to `npm` and `bower` tomorrow.

**Comment by rctneil** [comment]
Excellent. Thanks

**Comment by ghost** [comment]
Hello @rctneil, inStyle is now available in the Bower repository.

`bower install inStyle` or `bower install instyle`

And on NPM:

`npm install inStyle`

Unfortunately, the lowercase `instyle` version on NPM was already taken.
