### ISSUE TITLE
Replace not working as expected

### ISSUE THREAD

**Issue by Hannes-III** [salsita/chili#12]
Today I read your article on CSS Tricks and hat to play around with inStyle immediately, because I know the Problem and was lucky that now there is a solution.
I was really impressed, as I found out, that there is even a replace functionality. I tested out everything, And I am really imprressed, Really cool tool.
But then I found something that did not work as expected, maybe that should be mentioned in the documentation:

``` SCSS
.x1{
    .x2{
        .x3{
            .current{
                @include in(  "@.y3"){...}     //OK    .x1 .x2 .y3 .current {..}
                @include in( "@@.y2"){...}     //OK    .x1 .y2 .x3 .current {..}
                @include in("@@@.y1"){...}     //OK    .y1 .x2 .x3 .current {..}
                @include in("@@.y2 @.y1"){...} //ERROR .y2 .x2 .y1 .current {..}
                @include in("@.y1 @@.y2"){...} //ERROR .y1 .y2 .x3 .current {..}
            }
        }
    }
}
```

I found out, if I replace more then one element in the selector pattern, the amount of "@" infront of the replace-with pattern is not seen as an absolute value but relative to the last match. This was not what I had expected.

**Comment by ghost** [comment]
Hi @Hannes-III , you are correct in saying that all the matches are relative to either the first element above the current or the previously matched index - I see I have removed this from the documentation by accident while adding the replace feature recently. This behavior made more sense with the previous versions of the plugin, but perhaps it isn't so anymore. As you've filed this bug, I suppose the current behavior is not naturally expected - and I'd like to avoid that. Would you say that always working from the base index should be the expected default?

**Comment by ghost** [comment]
Hi @Hannes-III,

I have been pondering this issue over the last few days and decided to rewrite the parser to always work from the base index and allow modifications written in any order, as the current parser flow restrictions make little positive impact coupled with the new features - on the contrary, I feel it is just complicating things. Your code sample will work as expected in 1.6.0, which should be out in a matter of days (probably tomorrow).

**Comment by ghost** [comment]
1.6.0 has just been released, which solves this issue.

**Comment by Hannes-III** [comment]
Sorry I was busy the last days. Yes, you have been right:

> Would you say that always working from the base index should be the expected default?
> _**YES!**_

Thank you, I have just downloaded the new version and tested my code. Now it works as expected.
For those interested how it works now, here is the example how it works now:

``` SCSS
.x1{
    .x2{
        .x3{
            .current{
                @include in(  "@.y3"){...}     //OK    .x1 .x2 .y3 .current {..}
                @include in( "@@.y2"){...}     //OK    .x1 .y2 .x3 .current {..}
                @include in("@@@.y1"){...}     //OK    .y1 .x2 .x3 .current {..}
                @include in("@@.y2 @.y3"){...} //NEW   .x1 .y2 .y3 .current {..}
                @include in("@.y3 @@.y2"){...} //NEW   .x1 .y2 .y3 .current {..}
                @include in("@.y3 @@@.y1"){...} //NEW  .y1 .x2 .y3 .current {..}
            }
        }
    }
}
```

Thank you, I have already used `@include in()` already about 10 times in my current project.
